### ISSUE TITLE
Cant find demo scene

### ISSUE THREAD

**Issue by ghost** [OpenKit/openkit-unity#2]
Just download OpenKitUnityPlugin.1.0.unitypackage but cant find demo scene.
Some days before i download OpenKitUnityPlugin_0.8.9.unitypackage, there is a demoscene but many methods change since there.

**Comment by toddham** [comment]
There is a demo scene that shows OpenKit login, leaderboards, and submitting scores copied into Assets/, called OKDemoScene with a corresponding script, OKDemoScene.cs
